config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

pybo/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    subject = models.CharField(max_length=200)  # 제목
    content = models.TextField() # 내용
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # Foreign Key 선언, 질문 삭제시 Cascading하게 삭제됨
    content = models.TextField()  # 답변 내용
    create_date = models.DateTimeField()  # 답변 작성 시각

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    """
    장고의 폼은 forms.Form과 forms.ModelForm 두 가지
    모델 폼은 모델과 연결되어 폼을 저장하며, 모델의 데이터를 저장한다.
    Meta class를 override해서 어떤 모델을 사용하고, 그 모델의 어떤 field를 쓸 것인지 써둔다.
    """
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # Question Form에서 사용할 Question Model의 속성
        """
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        # widgets를 Meta에 추가해 attrs를 통해 bootstrap class를 추가할 수 있다.
        # question_form의 {{ form.as_p }} 자동 렌더링 코드를 바꿔줄 것이라 주석처리.
        """
        labels = {
            'subject': '제목',
            'content': '내용',
        }
        # labels를 등록해 모델의 attribute이름의 표시를 바꾼다.


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from .models import Question
from .forms import QuestionForm, AnswerForm


# Create your views here.
def index(request):
    """
    create_date로 역정렬한(-가 inverse) Question의 Objects를 question_list로 만듦
    render는 파이썬 데이터를 HTML로 템플릿에 적용해 반환한다.
    """
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question=question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible')
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    # question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    """
    from .models import Answer
    
    question = get_object_or_404(Question, pk=question_id)
    answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    answer.save()
    """
    # return redirect('pybo:detail', question_id=question.id)


def question_create(request):
    """
    GET이면 question form을 views.question_form과 연결해 render해서 보여주고
    POST면 form을 request.POST에 들어간 값을 넣어서 생성하고, valid check 후,
    question에 저장 후 timedate넣어준 뒤 save한다.
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- Pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!--기본 템플릿 안에 삽입될 내용-->
{% block content %}
{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 끝-->
</body>
</html>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- Question -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- Answer -->
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- answer form -->
    <form action="{% url 'pybo:answer_create' question_id=question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류 표시 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류 표시 끝 -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">질문등록</h5>
        <form method="post">
            <!--
            form의 action은 form의 data를 보낼 Server의 url을 명시하는 데에 쓰이는 Tag다.
            form에 action을 지정하지 않은 이유, action="{% url 'pybo:question_create' %}"
            를 넣으면, 이 코드를 재활용 불가함. 질문 수정 등에서. action을 지정하지 않으면, 현 페이지의 url이
            default로 설정된다. -->
            {% csrf_token %}
            <!--{{ form.as_p }}수동 구현 -->
            <!-- views.py에서 render(request, 'pybo/question.html', {'form': form}
            으로 보내온 form을 렌더링하는 옵션이다. as_p는 paragraph, as_table은 table 등-->
            <!-- 오류 표시 -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류 표시 끝 -->
            <div class="mb-3">
                <label for="subject" class="form-label">제목</label>
                <input type="text" class="form-control" name="subject" id="subject"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="content" class="form-label">내용</label>
                <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                <!-- form.content.value는 오류시 기존 입력값 유지를 위함,
                default_if_none:''는 입력값 없을 때 None이 나오는 대신 ''를 출력하기 위함
                이를 Template Filter라고 한다. 앞에 |를 붙여 사용한다.-->
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question_id=question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}